### ISSUE TITLE
麻烦问一下！rf_privacy_category_classifier.py中的pc/pc.csv是什么文件啊？可以提供吗？

### ISSUE THREAD

**Issue by feichuanshuo** [das-lab/VioDroid-Finder#1]
如题

**Comment by cjrcjr** [comment]
您好，这个文件其实就是用于训练文本分类模型的数据集，即dataset/labelled_dataset.csv中的句子及pc标签。我把pc（privacy category）和cr（compliance rule）两种标签合并在labelled_dataset.csv文件中了

**Comment by feichuanshuo** [comment]
好的，非常感谢！
